name: test regsmart
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

env:
  REGSMART_PACKAGE: "git+https://github.com/leticosta4/pytest-regsmart@e8fe612271bc27698cd8285a535209262e8e1a03"

jobs:
  test:
    name: regsmart (${{ matrix.mode }})
    strategy:
      fail-fast: false
      matrix:
        - python-version: ["3.12"]
          mode: rgsm_qtf
          weight: "1-0"
        - python-version: ["3.12"]
          mode: rgsm_recentfail
          weight: "0-1"
        - python-version: ["3.12"]
          mode: rgsm_hybrid
          weight: "1-1"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Start external services
      run: docker compose up -d
    - name: Ensure pip >= v25.1
      run: python -m pip install "pip >= 25.1"
    - name: Install the project and its dependencies
      run: pip install --group test -e .
    
    - name: Install pytest-regsmart
      run: |
        pip install --system "$REGSMART_PACKAGE"
        pip freeze --system

    - name: Restore pytest-regsmart cache
      id: restore-pytest-regsmart-cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/.pytest_cache/v/pytest_ranked_selection_data
        key: pytest-regsmart-cache-${{ github.workflow }}-${{ runner.os }}-${{ matrix.mode }}
        restore-keys: |
          pytest-regsmart-cache-${{ github.workflow }}-${{ runner.os }}-${{ matrix.mode }}-

    - name: Test with pytest
      run: coverage run -m pytest -v --regsmart --ranking-weight=${{ matrix.weight }}
      #eu tirei job de coverage aqui, talvez devesse manter
    
    - name: Save pytest-regsmart cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/.pytest_cache/v/pytest_ranked_selection_data
        key: pytest-regsmart-cache-${{ github.workflow }}-${{ runner.os }}-${{ matrix.mode }}-${{ github.run_id }}
